name: asToolkit.Client Build and Test

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'src/asToolkit.Domain/**'
      - 'src/asToolkit.Client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/asToolkit.Domain/**'
      - 'src/asToolkit.Client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Restore workloads
        run: dotnet workload restore src/asToolkit.Client/asToolkit.Client.csproj

      - name: Restore asToolkit.Client.Tests
        run: dotnet restore tests/asToolkit.Client.Tests -p:TargetFramework=net10.0
      - name: Build asToolkit.Client.Tests
        run: dotnet build tests/asToolkit.Client.Tests -p:TargetFramework=net10.0
      - name: Test asToolkit.Client.Tests
        run: dotnet test tests/asToolkit.Client.Tests --no-build --verbosity normal
